<?php
include 'admin/baglanti.php';
checkAuth();
$userId = (int) $_SESSION['kullanici_id'];
$cart = mysqli_query($conn, "SELECT s.adet, t.fiyat, t.img, m.model_ad, h.hafiza_ad FROM sepet s JOIN telefon t ON t.id=s.telefon_id LEFT JOIN model m ON m.model_id=t.model_id LEFT JOIN hafiza h ON h.hafiza_id=t.hafiza_id WHERE s.kullanici_id=$userId");
$items=[]; $total=0; $count=0;
while($item=mysqli_fetch_assoc($cart)){ $item['line_total']=(float)$item['fiyat']*(int)$item['adet']; $items[]=$item; $total += $item['line_total']; $count += (int)$item['adet']; }
if (!$items) { header('Location: sepet.php'); exit; }
$addressResult = mysqli_query($conn, "SELECT a.*, m.mahalle_adi AS mahalle, c.ilce_adi AS ilce, i.il_adi AS il FROM kullanici_adresleri a JOIN mahalleler m ON m.id=a.mahalle_id JOIN ilceler c ON c.id=m.ilce_id JOIN iller i ON i.id=c.il_id WHERE a.kullanici_id=$userId ORDER BY a.id DESC");
$addresses=[]; while($address=mysqli_fetch_assoc($addressResult)) $addresses[]=$address;
$formattedTotal=number_format($total,2,',','.');
?>
<!doctype html>
<html lang="tr"><head><?php include 'parts/head.php'; ?><link rel="stylesheet" href="assets/css/account.css"></head><body>
<?php include 'parts/header.php'; ?>
<main class="account-page checkout-page"><div class="checkout-steps"><span class="done"><i class="bi bi-check2"></i> Sepet</span><b></b><span class="active">2&nbsp; Ödeme</span><b></b><span>3&nbsp; Sipariş tamamlandı</span></div><div class="page-intro"><div><span class="eyebrow">Güvenli ödeme</span><h1>Siparişi tamamla</h1><p>Bilgilerini kontrol et, ödeme seçeneğini belirle ve siparişini oluştur.</p></div></div>
<form action="odeme_tamamla.php" method="post"><div class="checkout-grid"><div class="checkout-main"><section class="checkout-card"><div class="card-heading"><div><span class="eyebrow">01 · Teslimat</span><h2>Teslimat adresi</h2></div><a href="profil.php">Adres yönetimi</a></div><?php if (!$addresses): ?><div class="checkout-empty"><i class="bi bi-geo-alt"></i><p>Ödeme için önce bir teslimat adresi eklemelisin.</p><a href="profil.php" class="btn btn-light">Profilime git</a></div><?php else: ?><div class="address-options"><?php foreach($addresses as $key=>$address): ?><label class="address-option"><input type="radio" name="adres_id" value="<?= (int)$address['id'] ?>" <?= $key===0?'checked':'' ?> required><span><b><?= htmlspecialchars($address['adres_basligi']) ?></b><small><?= htmlspecialchars($address['il'].' / '.$address['ilce'].' / '.$address['mahalle']) ?><br><?= htmlspecialchars($address['adres_detay']) ?></small></span><i class="bi bi-check-circle-fill"></i></label><?php endforeach; ?></div><?php endif; ?></section>
<section class="checkout-card"><div class="card-heading"><div><span class="eyebrow">02 · Ödeme</span><h2>Ödeme yöntemi</h2></div></div><div class="payment-options"><label class="payment-option"><input type="radio" name="odeme_secimi" value="taksitli" checked><span><i class="bi bi-credit-card-2-front"></i><b>Kart ile ödeme</b><small>Tek çekim veya taksit seçenekleri</small></span><i class="bi bi-check-circle-fill"></i></label><label class="payment-option"><input type="radio" name="odeme_secimi" value="aninda_havale"><span><i class="bi bi-bank"></i><b>Anında havale</b><small>Bankanızdan hızlı ve güvenli transfer</small></span><i class="bi bi-check-circle-fill"></i></label></div><div class="installment-note"><i class="bi bi-info-circle"></i> Ödeme bilgilerin güvenli altyapımızla korunur.</div></section></div>
<aside class="summary-card checkout-summary"><span class="eyebrow">Sipariş özeti</span><h2><?= $count ?> ürün</h2><div class="checkout-products"><?php foreach($items as $item): ?><div><img src="assets/img/<?= htmlspecialchars($item['img']) ?>" alt=""><span><?= htmlspecialchars($item['model_ad'].' '.$item['hafiza_ad']) ?><small><?= (int)$item['adet'] ?> adet</small></span><b><?= number_format($item['line_total'],2,',','.') ?> TL</b></div><?php endforeach; ?></div><hr><div class="summary-row"><span>Ara toplam</span><b><?= $formattedTotal ?> TL</b></div><div class="summary-row"><span>Kargo</span><b class="success-text">Ücretsiz</b></div><div class="summary-total"><span>Toplam</span><strong><?= $formattedTotal ?> TL</strong></div><?php if ($addresses): ?><label class="terms-check"><input name="sozlesme_checkbox" value="1" type="checkbox" required><span>Mesafeli satış sözleşmesini ve ön bilgilendirme formunu okudum, onaylıyorum.</span></label><button class="btn btn-brand summary-button" type="submit">Siparişi onayla <i class="bi bi-arrow-right"></i></button><?php else: ?><a href="profil.php" class="btn btn-brand summary-button">Adres ekle <i class="bi bi-arrow-right"></i></a><?php endif; ?><div class="secure-note"><i class="bi bi-shield-check"></i> SSL ile güvenli ödeme</div></aside></div></form></main>
<?php include 'parts/footer.php'; ?></body></html>
