<?php
include 'baglanti.php';
checkAdmin();
$users = (int) (mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) total FROM kullanici"))['total'] ?? 0);
$products = (int) (mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) total FROM telefon"))['total'] ?? 0);
$stock = (int) (mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) total FROM telefon WHERE stok_id=2 OR stok_adet=0"))['total'] ?? 0);
$orders = 0;
$hasOrders = mysqli_num_rows(mysqli_query($conn, "SHOW TABLES LIKE 'siparisler'")) > 0;
if ($hasOrders) $orders = (int) (mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) total FROM siparisler"))['total'] ?? 0);
$latest = mysqli_query($conn, "SELECT t.id, t.img, t.fiyat, t.stok_adet, m.model_ad, h.hafiza_ad FROM telefon t LEFT JOIN model m ON m.model_id=t.model_id LEFT JOIN hafiza h ON h.hafiza_id=t.hafiza_id ORDER BY t.id DESC LIMIT 5");
?>
<!doctype html>
<html lang="tr"><head><?php include 'a-parts/head.php'; ?></head><body>
<div class="container-fluid d-flex w-100 min-vh-100 p-0"><?php include 'a-parts/header.php'; ?><main class="content"><?php include 'a-parts/content_top.php'; ?>
<div class="admin-dashboard"><div class="admin-heading"><div><span class="eyebrow">Kontrol merkezi</span><h1>Dashboard</h1><p>Mağazanın bugünkü özeti.</p></div><a href="telefon_ekle.php" class="admin-primary"><i class="bi bi-plus-lg"></i> Yeni ürün</a></div>
<div class="admin-stats"><article><span class="admin-stat-icon purple"><i class="bi bi-people"></i></span><small>Toplam kullanıcı</small><strong><?= $users ?></strong><a href="kullanicilar.php">Kullanıcıları gör <i class="bi bi-arrow-up-right"></i></a></article><article><span class="admin-stat-icon blue"><i class="bi bi-box-seam"></i></span><small>Aktif ürün</small><strong><?= $products ?></strong><a href="telefon.php">Ürünleri yönet <i class="bi bi-arrow-up-right"></i></a></article><article><span class="admin-stat-icon orange"><i class="bi bi-cart-check"></i></span><small>Toplam sipariş</small><strong><?= $orders ?></strong><a href="../siparisler.php">Siparişleri gör <i class="bi bi-arrow-up-right"></i></a></article><article><span class="admin-stat-icon red"><i class="bi bi-exclamation-triangle"></i></span><small>Stok uyarısı</small><strong><?= $stock ?></strong><a href="telefon.php">Kontrol et <i class="bi bi-arrow-up-right"></i></a></article></div>
<div class="admin-columns"><section class="admin-panel"><div class="admin-panel-head"><div><span class="eyebrow">Katalog</span><h2>Son eklenen ürünler</h2></div><a href="telefon.php">Tümünü gör</a></div><div class="admin-products"><?php while($product=mysqli_fetch_assoc($latest)): ?><div class="admin-product"><img src="../assets/img/<?= htmlspecialchars($product['img']) ?>" alt=""><span><b><?= htmlspecialchars(trim($product['model_ad'].' '.$product['hafiza_ad'])) ?></b><small><?= number_format((float)$product['fiyat'],2,',','.') ?> TL</small></span><em class="<?= (int)$product['stok_adet'] > 0 ? 'in-stock' : 'out-stock' ?>"><?= (int)$product['stok_adet'] > 0 ? 'Stokta' : 'Tükendi' ?></em></div><?php endwhile; ?></div></section><section class="admin-panel admin-quick"><div class="admin-panel-head"><div><span class="eyebrow">Hızlı işlemler</span><h2>Ne yapmak istersin?</h2></div></div><a href="telefon_ekle.php"><i class="bi bi-phone"></i><span><b>Ürün ekle</b><small>Kataloğa yeni ürün ekle</small></span><i class="bi bi-arrow-up-right"></i></a><a href="model_ekle.php"><i class="bi bi-tag"></i><span><b>Model oluştur</b><small>Yeni cihaz modeli tanımla</small></span><i class="bi bi-arrow-up-right"></i></a><a href="../index.php"><i class="bi bi-shop"></i><span><b>Mağazayı görüntüle</b><small>Yayındaki siteyi aç</small></span><i class="bi bi-arrow-up-right"></i></a></section></div></div></main></div><script src="../assets/js/admin.js"></script></body></html>
